spring.application.name=user_management
server.port=8181

# Database configuration
spring.datasource.url=jdbc:postgresql://172.28.183.147:5432/user_management_db?ssl=false
spring.datasource.username=developer
spring.datasource.password=devjava2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.show_sql=true

# Logging configuration
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

