### Configuración de Variables
@baseUrl = http://localhost:8080/api/v1/auth
@contentType = application/json

### 1. Registrar un nuevo usuario (Register)
# Este método encriptará la contraseña y guardará al usuario en login_user
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
    "email": "anakin@java.com",
    "password": "LadoOscur0!",
    "userName": "Anakin",
    "lastName": "Skywalker",
    "authProvider": "LOCAL",
    "roleUser": "ROLE_ADMIN"
}

### 2. Iniciar sesión (Login)
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "test.user@smartbilling.ai",
    "password": "Password123!"
}

### Guardar el Token del login anterior
@authToken = {{login.response.body.token}}

### 3. Ejemplo de prueba para una ruta protegida (Opcional)
# Una vez tengas otros controladores, usa esta estructura para probar el JWT
GET http://localhost:8080/api/v1/customers
Authorization: Bearer {{authToken}}